# Generated by Django 4.2.2 on 2023-06-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_attachment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='comment',
        ),
    ]
