# Generated by Django 4.2.2 on 2023-06-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_attachment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='comment',
        ),
    ]
